services:
  db:
    image: mysql
    ports:
      - "3399:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "5566"
    volumes:
      - vol1:/var/lib/mysql

  web:
    image: wordpress
    ports:
      - "5555:80"
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "admin"
      WORDPRESS_DB_PASSWORD: "5566"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - vol1:/var/www/html
